basic_app/urls.py
from django.urls import path
from . import views

app_name = 'basic_app'

urlpatterns = [
    path('', views.SekolahListView.as_view(), name='list'),
    path('sekolah/<int:pk>', views.SekolahDetailView.as_view(), name='sekolahdetail'),
    path('buat/', views.SekolahCreateView.as_view(), name='buat'),
    path('update/<int:pk>', views.SekolahUpdateView.as_view(), name='update'),
    path('hapus/<int:pk>', views.SekolahHapusView.as_view(), name='hapus'),
]

cbv/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('cbv', views.CBView.as_view(), name='cbv'),
    path('cbvindex', views.IndexCBVView.as_view(), name='indexcbv'),
    path('basic_app/', include('basic_app.urls', namespace='basic_app')),
]

basic_app/models.py
from django.db import models
from django.urls import reverse


# Create your models here.
class Sekolah(models.Model):
    nama = models.CharField(max_length=200)
    kepsek = models.CharField(max_length=200)
    lokasi = models.CharField(max_length=200)

    def __str__(self):
        return self.nama

    # url setelah selesai post akan redirect kemana
    def get_absolute_url(self):
        return reverse('basic_app:sekolahdetail', kwargs={'pk': self.pk})



class Murid(models.Model):
    nama = models.CharField(max_length=200)
    umur = models.PositiveIntegerField()
    sekolah = models.ForeignKey(Sekolah, related_name='siswa', on_delete=models.CASCADE)

    def __str__(self):
        return self.nama

basic_app/views.py
from django.shortcuts import render
from django.views.generic import (View, 
                                    TemplateView, ListView, DetailView,
                                    CreateView, UpdateView, DeleteView)
from django.http import HttpResponse
from .models import Sekolah, Murid
from django.urls import reverse_lazy


# Create your views here.
# view cara lama pakai function
def index(request):
    return render(request, 'index.html', {'page_title':'Index dengan Function Based Views'})

# view dengan class based view
class CBView(View):
    def get(self, request):
        return HttpResponse('CBV')


class IndexCBVView(TemplateView):
    template_name = 'index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Index dengan Class Based Views'
        return context


class SekolahListView(ListView):
    model = Sekolah
    context_object_name = 'daftar_sekolah'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Selamat datang di Halaman Daftar Sekolah'
        return context


class SekolahDetailView(DetailView):
    model = Sekolah
    context_object_name = 'detail_sekolah'
    template_name = 'basic_app/sekolah_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Selamat datang di Halaman Detail Sekolah'
        return context


class SekolahCreateView(CreateView):
    fields = ('nama', 'kepsek', 'lokasi')
    model = Sekolah

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Form Data Sekolah'
        return context


class SekolahUpdateView(UpdateView):
    fields = ('nama', 'kepsek')
    model = Sekolah

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Form Data Sekolah'
        return context


class SekolahHapusView(DeleteView):
    model = Sekolah

    success_url = reverse_lazy('basic_app:list')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = 'Hapus Sekolah'
        return context

basic_app/templates/basic_app/basic_app_base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>{{page_title}}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'indexcbv' %}">
          <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">
          Class Based Views
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto flex-nowrap">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:list' %}">Daftar Sekolah</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Daftar Sekolah</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>

      </div>
    </nav>

    <main class="container">
        {% block body_block %} {% endblock %}
      </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

basic_app/templates/basic_app/sekolah_confirm_delete.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %} 

<div class="p-5 mb-4 bg-light rounded-3">
    <h1>{{ page_title }} {{sekolah.nama}} ?</h1>

    <form method="POST">
        {% csrf_token %}

        <button type="submit" class="btn btn-danger btn-lg">Hapus Data</button>
        <a href="{% url 'basic_app:sekolahdetail' sekolah.id %}" class="btn btn-info btn-lg">Batal</a>

    </form>

</div>


{% endblock %}

basic_app/templates/basic_app/sekolah_detail.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %} 

<div class="p-5 mb-4 bg-light rounded-3">
    <h1>{{ page_title }}</h1>

    <h2>Detail Sekolah:</h2>
    <p>Nama Sekolah : {{ detail_sekolah.nama}}</p>
    <p>Kepala Sekolah : {{ detail_sekolah.kepsek}}</p>
    <p>Lokasi : {{ detail_sekolah.lokasi}}</p>

    <h2>Murid</h2>
    {% for murid in detail_sekolah.siswa.all %}
        <p>{{murid.nama}} Umur {{murid.umur}}</p>
    {% endfor %}

</div>


<div class="container">
    <p><a class="btn btn-outline-success" href="{% url 'basic_app:update' pk=detail_sekolah.pk %}">Update</a></p>
    <p><a class="btn btn-outline-danger" href="{% url 'basic_app:hapus' pk=detail_sekolah.pk %}">Hapus</a></p>
</div>

{% endblock %}

basic_app/templates/basic_app/sekolah_form.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %} 

<div class="p-5 mb-4 bg-light rounded-3">
    <h1>{{ page_title }}</h1>

    {# kalau belum ada PK atau ada data berarti buat baru #}
    {% if not form.instance.pk %}
        <h2>Buat Data Baru</h2>
    {% else %}
        <h2>Update Data</h2>
    {% endif %}

    <form method="POST">
        {% csrf_token %}

        {{ form.as_p }}

        <button type="submit" class="btn btn-primary btn-lg">Simpan Data</button>

    </form>

</div>


{% endblock %}

basic_app/templates/basic_app/sekolah_list.html
{% extends "basic_app/basic_app_base.html" %}

{% block body_block %} 

<div class="p-5 mb-4 bg-light rounded-3">
    <h1>{{ page_title }}</h1>

    <ol>
        {% for sekolah in daftar_sekolah %}
        <h2>
            <li><a href="{% url 'basic_app:sekolahdetail' sekolah.id %}">{{ sekolah.nama}}</a></li>
        </h2>
        {% endfor %}
    </ol>

</div>


{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <title>{{page_title}}</title>
  </head>
  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark mb-4">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'indexcbv' %}">
          <img src="https://getbootstrap.com/docs/5.0/assets/brand/bootstrap-logo.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">
          Class Based Views
        </a>

        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav ms-auto flex-nowrap">
            <li class="nav-item">
              <a class="nav-link" aria-current="page" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'basic_app:list' %}">Daftar Sekolah</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Daftar Sekolah</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
            </li>
          </ul>
        </div>

      </div>
    </nav>

    <main class="container">
        {% block body_block %} {% endblock %}
      </main>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/index.html
{% extends "base.html" %}

{% block body_block %} 

<div class="p-5 mb-4 bg-light rounded-3">
    <h1>{{ page_title }}</h1>
</div>


{% endblock %}